""" delete family_name & age & nationality


Revision ID: 5eec571d9ac3
Revises: cd9dc93a2763
Create Date: 2025-10-22 17:52:06.767174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eec571d9ac3'
down_revision: Union[str, Sequence[str], None] = 'cd9dc93a2763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'nationality')
    op.drop_column('machine', 'family_name')
    op.drop_column('machine', 'address')
    op.drop_column('machine', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('machine', sa.Column('address', sa.VARCHAR(length=100), nullable=True))
    op.add_column('machine', sa.Column('family_name', sa.VARCHAR(length=20), nullable=True))
    op.add_column('machine', sa.Column('nationality', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
