"""Add age field

Revision ID: d50eb72e637c
Revises: 55b699cd69f7
Create Date: 2025-10-22 14:58:15.188956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50eb72e637c'
down_revision: Union[str, Sequence[str], None] = '55b699cd69f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'age')
    # ### end Alembic commands ###
