""" delete nationality

Revision ID: 1a58912bad0a
Revises: 360e16875aca
Create Date: 2025-10-22 16:21:38.991253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a58912bad0a'
down_revision: Union[str, Sequence[str], None] = '360e16875aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'nationality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('nationality', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
