""" add  nationality

Revision ID: 4abcfee3fd98
Revises: 1a58912bad0a
Create Date: 2025-10-22 16:22:15.063786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4abcfee3fd98'
down_revision: Union[str, Sequence[str], None] = '1a58912bad0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'nationality')
    # ### end Alembic commands ###
